In [4]:
import pandas as pd
import numpy as np

In [18]:
ds1 = pd.read_csv("student_mental_health_burnout.csv")
ds2 = pd.read_csv("Social_media_impact_on_life.csv")
ds3 = pd.read_csv("Student Mental Health Analysis During Online Learning.csv")
ds4 = pd.read_csv("Student Mental Health.csv")

In [19]:
ds1.head()

,student_id,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,100001,23,Male,BTech,1st,4.3,6.8,6.1,High,10,3,4,2,6,1.8,Average,66.5,9.63,Good,High
1,100002,20,Male,BTech,3rd,1.4,4.7,3.0,High,2,10,8,5,9,1.9,Poor,55.8,6.04,Poor,Low
2,100003,24,Female,BCA,4th,3.7,4.8,1.5,Low,2,7,8,6,3,0.8,Good,85.0,8.31,Good,High
3,100004,21,Male,BSc,4th,1.6,6.7,7.0,High,3,3,4,9,9,0.7,Poor,89.1,5.95,Good,High
4,100005,23,Other,BSc,4th,2.0,6.7,5.4,High,7,7,6,4,4,1.7,Good,58.7,8.51,Good,Low

In [20]:
ds2.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Overall_Impact
0,232,21,Male,Undergraduate,Other,4.0,Facebook,No,6.7,6.8,Neutral
1,564,23,Female,Undergraduate,Other,1.6,LinkedIn,No,8.6,7.6,Positive
2,788,22,Male,Graduate,Canada,4.6,Instagram,No,6.7,7.0,Neutral
3,686,18,Male,Undergraduate,Other,7.0,Snapchat,Yes,5.4,5.3,Negative
4,608,24,Female,High School,Other,7.5,Facebook,Yes,5.0,4.4,Negative

In [21]:
ds3.head()

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Aarav,Male,15,Class 8,7.1,8.9,9.3,Medium,No,Same
1,Meera,Female,25,MSc,3.3,5.0,0.2,Medium,No,Same
2,Ishaan,Male,20,BTech,9.5,5.4,6.2,Medium,No,Same
3,Aditya,Male,20,BA,10.8,5.6,5.5,High,Yes,Same
4,Anika,Female,17,Class 11,2.8,5.4,3.1,Medium,Yes,Same

In [22]:
ds4.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [23]:
ds1.columns

Index(['student_id', 'age', 'gender', 'course', 'year', 'daily_study_hours',
       'daily_sleep_hours', 'screen_time_hours', 'stress_level',
       'anxiety_score', 'depression_score', 'academic_pressure_score',
       'financial_stress_score', 'social_support_score',
       'physical_activity_hours', 'sleep_quality', 'attendance_percentage',
       'cgpa', 'internet_quality', 'burnout_level'],
      dtype='object')

In [24]:
ds2.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Overall_Impact'],
      dtype='object')

In [25]:
ds3.columns

Index(['Name', 'Gender', 'Age', 'Education Level', 'Screen Time (hrs/day)',
       'Sleep Duration (hrs)', 'Physical Activity (hrs/week)', 'Stress Level',
       'Anxious Before Exams', 'Academic Performance Change'],
      dtype='object')

In [26]:
ds4.columns

Index(['Timestamp', 'Choose your gender', 'Age', 'What is your course?',
       'Your current year of Study', 'What is your CGPA?', 'Marital status',
       'Do you have Depression?', 'Do you have Anxiety?',
       'Do you have Panic attack?',
       'Did you seek any specialist for a treatment?'],
      dtype='object')

In [27]:
ds1.shape
ds2.shape
ds3.shape
ds4.shape

(101, 11)

In [28]:
ds1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   student_id               150000 non-null  int64
 1   age                      150000 non-null  int64
 2   gender                   150000 non-null  object
 3   course                   150000 non-null  object
 4   year                     150000 non-null  object
 5   daily_study_hours        150000 non-null  float64
 6   daily_sleep_hours        150000 non-null  float64
 7   screen_time_hours        150000 non-null  float64
 8   stress_level             150000 non-null  object
 9   anxiety_score            150000 non-null  int64
 10  depression_score         150000 non-null  int64
 11  academic_pressure_score  150000 non-null  int64
 12  financial_stress_score   150000 non-null  int64
 13  social_support_score     150000 non-null  int64
 14  physical_activity_hours  150000 non-null  float64
 15  sleep_quality            150000 non-null  object
 16  attendance_percentage    150000 non-null  float64
 17  cgpa                     150000 non-null  float64
 18  internet_quality         150000 non-null  object
 19  burnout_level            150000 non-null  object
dtypes: float64(6), int64(7), object(7)
memory usage: 22.9+ MB

In [29]:
ds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1705 non-null   int64
 1   Age                           1705 non-null   int64
 2   Gender                        1705 non-null   object
 3   Academic_Level                1705 non-null   object
 4   Country                       1705 non-null   object
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   object
 7   Affects_Academic_Performance  1705 non-null   object
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   object
dtypes: float64(3), int64(2), object(6)
memory usage: 146.7+ KB

In [30]:
ds3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Name                          1000 non-null   object
 1   Gender                        1000 non-null   object
 2   Age                           1000 non-null   int64
 3   Education Level               1000 non-null   object
 4   Screen Time (hrs/day)         1000 non-null   float64
 5   Sleep Duration (hrs)          1000 non-null   float64
 6   Physical Activity (hrs/week)  1000 non-null   float64
 7   Stress Level                  1000 non-null   object
 8   Anxious Before Exams          1000 non-null   object
 9   Academic Performance Change   1000 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 78.3+ KB

In [31]:
ds4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

In [33]:
ds1.isnull().sum()

student_id                 0
age                        0
gender                     0
course                     0
year                       0
daily_study_hours          0
daily_sleep_hours          0
screen_time_hours          0
stress_level               0
anxiety_score              0
depression_score           0
academic_pressure_score    0
financial_stress_score     0
social_support_score       0
physical_activity_hours    0
sleep_quality              0
attendance_percentage      0
cgpa                       0
internet_quality           0
burnout_level              0
dtype: int64

In [34]:
ds2.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Overall_Impact                  0
dtype: int64

In [36]:
ds3.isnull().sum()

Name                            0
Gender                          0
Age                             0
Education Level                 0
Screen Time (hrs/day)           0
Sleep Duration (hrs)            0
Physical Activity (hrs/week)    0
Stress Level                    0
Anxious Before Exams            0
Academic Performance Change     0
dtype: int64

In [37]:
ds4.isnull().sum()

Timestamp                                       0
Choose your gender                              0
Age                                             1
What is your course?                            0
Your current year of Study                      0
What is your CGPA?                              0
Marital status                                  0
Do you have Depression?                         0
Do you have Anxiety?                            0
Do you have Panic attack?                       0
Did you seek any specialist for a treatment?    0
dtype: int64

In [40]:
ds1 = ds1.drop(columns=[
    'student_id',
    'course',
    'financial_stress_score',
    'attendance_percentage',
    'cgpa',
    'internet_quality'
])

In [41]:
ds1.head()

,age,gender,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,social_support_score,physical_activity_hours,sleep_quality,burnout_level
0,23,Male,1st,4.3,6.8,6.1,High,10,3,4,6,1.8,Average,High
1,20,Male,3rd,1.4,4.7,3.0,High,2,10,8,9,1.9,Poor,Low
2,24,Female,4th,3.7,4.8,1.5,Low,2,7,8,3,0.8,Good,High
3,21,Male,4th,1.6,6.7,7.0,High,3,3,4,9,0.7,Poor,High
4,23,Other,4th,2.0,6.7,5.4,High,7,7,6,4,1.7,Good,Low

In [44]:
ds2 = ds2.drop(columns=[
    'Student_ID',
    'Country',
    'Age',
    'Gender',
    'Academic_Level',
    'Sleep_Hours_Per_Night',
    'Overall_Impact'
])

In [45]:
ds2.head()

,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Mental_Health_Score
0,4.0,Facebook,No,6.8
1,1.6,LinkedIn,No,7.6
2,4.6,Instagram,No,7.0
3,7.0,Snapchat,Yes,5.3
4,7.5,Facebook,Yes,4.4

In [46]:
ds3 = ds3[[
    'Anxious Before Exams',
    'Academic Performance Change'
]]

In [47]:
ds3.head()

  Anxious Before Exams Academic Performance Change
0                   No                        Same
1                   No                        Same
2                   No                        Same
3                  Yes                        Same
4                  Yes                        Same

In [48]:
ds4 = ds4[[
    'Do you have Depression?',
    'Do you have Panic attack?'
]]

In [49]:
ds4.head()

  Do you have Depression? Do you have Panic attack?
0                     Yes                       Yes
1                      No                        No
2                     Yes                       Yes
3                     Yes                        No
4                      No                        No

In [51]:
ds1 = ds1.drop_duplicates()
ds2 = ds2.drop_duplicates()
ds3 = ds3.drop_duplicates()
ds4 = ds4.drop_duplicates()

In [52]:
ds1.isnull().sum()

age                        0
gender                     0
year                       0
daily_study_hours          0
daily_sleep_hours          0
screen_time_hours          0
stress_level               0
anxiety_score              0
depression_score           0
academic_pressure_score    0
social_support_score       0
physical_activity_hours    0
sleep_quality              0
burnout_level              0
dtype: int64

In [53]:
ds2.isnull().sum()

Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Mental_Health_Score             0
dtype: int64

In [54]:
ds3.isnull().sum()

Anxious Before Exams           0
Academic Performance Change    0
dtype: int64

In [55]:
ds4.isnull().sum()

Do you have Depression?      0
Do you have Panic attack?    0
dtype: int64