In [69]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# File Loading

In [127]:
df = pd.read_csv('/content/raw/student_mental_health_burnout.csv')
ds1 = pd.read_csv('/content/raw/Social_media_impact_on_life.csv')
ds2 = pd.read_csv('/content/raw/Student Mental Health Analysis During Online Learning.csv')
ds3 = pd.read_csv('/content/raw/Student Mental health.csv')

# Exploring Data

In [71]:
df.head()

,student_id,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,100001,23,Male,BTech,1st,4.3,6.8,6.1,High,10,3,4,2,6,1.8,Average,66.5,9.63,Good,High
1,100002,20,Male,BTech,3rd,1.4,4.7,3.0,High,2,10,8,5,9,1.9,Poor,55.8,6.04,Poor,Low
2,100003,24,Female,BCA,4th,3.7,4.8,1.5,Low,2,7,8,6,3,0.8,Good,85.0,8.31,Good,High
3,100004,21,Male,BSc,4th,1.6,6.7,7.0,High,3,3,4,9,9,0.7,Poor,89.1,5.95,Good,High
4,100005,23,Other,BSc,4th,2.0,6.7,5.4,High,7,7,6,4,4,1.7,Good,58.7,8.51,Good,Low

In [72]:
ds1.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Overall_Impact
0,232,21,Male,Undergraduate,Other,4.0,Facebook,No,6.7,6.8,Neutral
1,564,23,Female,Undergraduate,Other,1.6,LinkedIn,No,8.6,7.6,Positive
2,788,22,Male,Graduate,Canada,4.6,Instagram,No,6.7,7.0,Neutral
3,686,18,Male,Undergraduate,Other,7.0,Snapchat,Yes,5.4,5.3,Negative
4,608,24,Female,High School,Other,7.5,Facebook,Yes,5.0,4.4,Negative

In [73]:
ds2.head()

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Aarav,Male,15,Class 8,7.1,8.9,9.3,Medium,No,Same
1,Meera,Female,25,MSc,3.3,5.0,0.2,Medium,No,Same
2,Ishaan,Male,20,BTech,9.5,5.4,6.2,Medium,No,Same
3,Aditya,Male,20,BA,10.8,5.6,5.5,High,Yes,Same
4,Anika,Female,17,Class 11,2.8,5.4,3.1,Medium,Yes,Same

In [74]:
ds3.head()

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [75]:
df.columns

Index(['student_id', 'age', 'gender', 'course', 'year', 'daily_study_hours',
       'daily_sleep_hours', 'screen_time_hours', 'stress_level',
       'anxiety_score', 'depression_score', 'academic_pressure_score',
       'financial_stress_score', 'social_support_score',
       'physical_activity_hours', 'sleep_quality', 'attendance_percentage',
       'cgpa', 'internet_quality', 'burnout_level'],
      dtype='object')

In [76]:
ds1.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Overall_Impact'],
      dtype='object')

In [77]:
ds2.columns

Index(['Name', 'Gender', 'Age', 'Education Level', 'Screen Time (hrs/day)',
       'Sleep Duration (hrs)', 'Physical Activity (hrs/week)', 'Stress Level',
       'Anxious Before Exams', 'Academic Performance Change'],
      dtype='object')

In [78]:
ds3.columns

Index(['Timestamp', 'Choose your gender', 'Age', 'What is your course?',
       'Your current year of Study', 'What is your CGPA?', 'Marital status',
       'Do you have Depression?', 'Do you have Anxiety?',
       'Do you have Panic attack?',
       'Did you seek any specialist for a treatment?'],
      dtype='object')

In [79]:
df.shape
ds1.shape
ds2.shape
ds3.shape

(101, 11)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   student_id               150000 non-null  int64
 1   age                      150000 non-null  int64
 2   gender                   150000 non-null  object
 3   course                   150000 non-null  object
 4   year                     150000 non-null  object
 5   daily_study_hours        150000 non-null  float64
 6   daily_sleep_hours        150000 non-null  float64
 7   screen_time_hours        150000 non-null  float64
 8   stress_level             150000 non-null  object
 9   anxiety_score            150000 non-null  int64
 10  depression_score         150000 non-null  int64
 11  academic_pressure_score  150000 non-null  int64
 12  financial_stress_score   150000 non-null  int64
 13  social_support_score     150000 non-null  int64
 14  physical_activity_hours  150000 non-null  float64
 15  sleep_quality            150000 non-null  object
 16  attendance_percentage    150000 non-null  float64
 17  cgpa                     150000 non-null  float64
 18  internet_quality         150000 non-null  object
 19  burnout_level            150000 non-null  object
dtypes: float64(6), int64(7), object(7)
memory usage: 22.9+ MB

In [81]:
ds1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1705 non-null   int64
 1   Age                           1705 non-null   int64
 2   Gender                        1705 non-null   object
 3   Academic_Level                1705 non-null   object
 4   Country                       1705 non-null   object
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   object
 7   Affects_Academic_Performance  1705 non-null   object
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   object
dtypes: float64(3), int64(2), object(6)
memory usage: 146.7+ KB

In [82]:
ds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Name                          1000 non-null   object
 1   Gender                        1000 non-null   object
 2   Age                           1000 non-null   int64
 3   Education Level               1000 non-null   object
 4   Screen Time (hrs/day)         1000 non-null   float64
 5   Sleep Duration (hrs)          1000 non-null   float64
 6   Physical Activity (hrs/week)  1000 non-null   float64
 7   Stress Level                  1000 non-null   object
 8   Anxious Before Exams          1000 non-null   object
 9   Academic Performance Change   1000 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 78.3+ KB

In [83]:
ds3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

# Column Filtering

In [84]:
df = df.drop(columns=[
    'student_id',
    'course',
    'financial_stress_score',
    'attendance_percentage',
    'cgpa',
    'internet_quality'
])

In [85]:
df.head()

,age,gender,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,social_support_score,physical_activity_hours,sleep_quality,burnout_level
0,23,Male,1st,4.3,6.8,6.1,High,10,3,4,6,1.8,Average,High
1,20,Male,3rd,1.4,4.7,3.0,High,2,10,8,9,1.9,Poor,Low
2,24,Female,4th,3.7,4.8,1.5,Low,2,7,8,3,0.8,Good,High
3,21,Male,4th,1.6,6.7,7.0,High,3,3,4,9,0.7,Poor,High
4,23,Other,4th,2.0,6.7,5.4,High,7,7,6,4,1.7,Good,Low

In [86]:
ds1 = ds1.drop(columns=[
    'Student_ID',
    'Country',
    'Age',
    'Gender',
    'Academic_Level',
    'Sleep_Hours_Per_Night',
    'Overall_Impact'
])

In [87]:
ds1.head()

,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Mental_Health_Score
0,4.0,Facebook,No,6.8
1,1.6,LinkedIn,No,7.6
2,4.6,Instagram,No,7.0
3,7.0,Snapchat,Yes,5.3
4,7.5,Facebook,Yes,4.4

In [88]:
ds2 = ds2[[
    'Anxious Before Exams',
    'Academic Performance Change'
]]

In [89]:
ds2.head()

  Anxious Before Exams Academic Performance Change
0                   No                        Same
1                   No                        Same
2                   No                        Same
3                  Yes                        Same
4                  Yes                        Same

In [90]:
ds3 = ds3[[
    'Do you have Depression?',
    'Do you have Panic attack?'
]]

In [91]:
ds3.head()

  Do you have Depression? Do you have Panic attack?
0                     Yes                       Yes
1                      No                        No
2                     Yes                       Yes
3                     Yes                        No
4                      No                        No

In [92]:
df = df.drop_duplicates()
ds1 = ds1.drop_duplicates()
ds2 = ds2.drop_duplicates()
ds3 = ds3.drop_duplicates()

# Checking null values

In [93]:
df.isnull().sum()

age                        0
gender                     0
year                       0
daily_study_hours          0
daily_sleep_hours          0
screen_time_hours          0
stress_level               0
anxiety_score              0
depression_score           0
academic_pressure_score    0
social_support_score       0
physical_activity_hours    0
sleep_quality              0
burnout_level              0
dtype: int64

In [94]:
ds1.isnull().sum()

Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Mental_Health_Score             0
dtype: int64

In [95]:
ds2.isnull().sum()

Anxious Before Exams           0
Academic Performance Change    0
dtype: int64

In [96]:
ds3.isnull().sum()

Do you have Depression?      0
Do you have Panic attack?    0
dtype: int64

No missing values found

# Checking Outliers

In [97]:
df.describe()

,age,daily_study_hours,daily_sleep_hours,screen_time_hours,anxiety_score,depression_score,academic_pressure_score,social_support_score,physical_activity_hours
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,21.000380,5.507869,6.499361,6.502819,5.493907,5.497360,5.507427,5.516060,0.998115
std,2.581216,2.595592,1.443859,3.178948,2.872607,2.869022,2.875524,2.870493,0.578866
min,17.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,19.000000,3.300000,5.200000,3.700000,3.000000,3.000000,3.000000,3.000000,0.500000
50%,21.000000,5.500000,6.500000,6.500000,5.000000,5.000000,6.000000,6.000000,1.000000
75%,23.000000,7.700000,7.700000,9.300000,8.000000,8.000000,8.000000,8.000000,1.500000
max,25.000000,10.000000,9.000000,12.000000,10.000000,10.000000,10.000000,10.000000,2.000000

In [98]:
ds1.describe()

       Avg_Daily_Usage_Hours  Mental_Health_Score
count            1356.000000          1356.000000
mean                5.104499             6.246018
std                 1.787964             1.331400
min                 1.500000             4.000000
25%                 3.700000             5.000000
50%                 5.100000             6.000000
75%                 6.500000             7.025000
max                 8.500000             9.000000

In [99]:
ds2.describe()

       Anxious Before Exams Academic Performance Change
count                     6                           6
unique                    2                           3
top                      No                        Same
freq                      3                           2

In [100]:
ds3.describe()

       Do you have Depression? Do you have Panic attack?
count                        4                         4
unique                       2                         2
top                        Yes                       Yes
freq                         2                         2

# Making Column names standard

In [101]:
df.columns=(df.columns.str.lower().str.replace(" ","_"))

In [102]:
ds1.columns=(ds1.columns.str.lower().str.replace(" ","_"))

In [103]:
ds2.columns=(ds2.columns.str.lower().str.replace(" ","_"))

In [104]:
ds3.columns=(ds3.columns.str.lower().str.replace(" ","_"))

# Checking Unique Values

In [112]:
for col in ['gender','year','burnout_level','sleep_quality']:
  print(col)
  print(df[col].unique())

gender
['Male' 'Female' 'Other']
year
['1st' '3rd' '4th' '2nd']
burnout_level
['High' 'Low' 'Medium']
sleep_quality
['Average' 'Poor' 'Good']

# Burnout Distribution

In [115]:
df['burnout_level'].value_counts()

burnout_level
Low       50265
Medium    49969
High      49766
Name: count, dtype: int64

# Saving cleaned datasets

In [129]:
df.to_csv('/content/processed/burnout_cleaned.csv',index=False)
ds1.to_csv('/content/processed/social_media_cleaned.csv',index=False)
ds2.to_csv('/content/processed/online_learning_cleaned.csv',index=False)

# Encoding the categorical features

In [116]:
df_encoded=df.copy()
categorical_cols=['gender','year','burnout_level','sleep_quality']
encoder=LabelEncoder()
for col in categorical_cols:
  df_encoded[col]=encoder.fit_transform(df_encoded[col])

In [119]:
df_encoded.select_dtypes(include='object').columns

Index(['stress_level'], dtype='object')

In [120]:
df_encoded['stress_level'].unique()

array(['High', 'Low', 'Medium'], dtype=object)

In [121]:
stress_map={'High':2,'Medium':1,'Low':0}
df_encoded['stress_level']=df_encoded['stress_level'].map(stress_map)

# Correlation Check

In [122]:
corr=df_encoded.corr()
corr

,age,gender,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,social_support_score,physical_activity_hours,sleep_quality,burnout_level
age,1.000000,-0.003482,-0.002474,-0.000623,0.003084,-0.001495,0.000404,0.001606,-0.001968,0.000551,-0.000104,-0.003325,-0.001880,-0.001625
gender,-0.003482,1.000000,0.001713,0.003178,-0.002848,0.001644,-0.001753,0.000339,0.003705,0.003249,0.000438,0.000432,0.001651,-0.000061
year,-0.002474,0.001713,1.000000,-0.000196,-0.005758,0.000998,0.000088,0.002008,-0.001025,0.004184,-0.004901,0.000941,0.000222,-0.001361
daily_study_hours,-0.000623,0.003178,-0.000196,1.000000,-0.002353,0.001779,0.000289,0.002771,-0.001497,-0.003118,-0.003394,0.001722,-0.000679,-0.000609
daily_sleep_hours,0.003084,-0.002848,-0.005758,-0.002353,1.000000,0.001453,-0.001616,0.003168,-0.001608,-0.002160,-0.002535,-0.000076,-0.002641,0.003205
screen_time_hours,-0.001495,0.001644,0.000998,0.001779,0.001453,1.000000,0.000978,-0.000441,0.002552,-0.000651,-0.000779,-0.000003,0.001241,0.000833
stress_level,0.000404,-0.001753,0.000088,0.000289,-0.001616,0.000978,1.000000,0.001345,0.000777,0.001071,0.001184,-0.001643,0.002597,-0.003005
anxiety_score,0.001606,0.000339,0.002008,0.002771,0.003168,-0.000441,0.001345,1.000000,-0.001782,0.000503,0.002810,-0.001478,0.003308,0.001229
depression_score,-0.001968,0.003705,-0.001025,-0.001497,-0.001608,0.002552,0.000777,-0.001782,1.000000,0.000599,0.000227,0.001040,0.002245,0.001017
academic_pressure_score,0.000551,0.003249,0.004184,-0.003118,-0.002160,-0.000651,0.001071,0.000503,0.000599,1.000000,-0.002619,-0.000909,0.000921,-0.004231
social_support_score,-0.000104,0.000438,-0.004901,-0.003394,-0.002535,-0.000779,0.001184,0.002810,0.000227,-0.002619,1.000000,-0.007241,-0.002784,0.000226
physical_activity_hours,-0.003325,0.000432,0.000941,0.001722,-0.000076,-0.000003,-0.001643,-0.001478,0.001040,-0.000909,-0.007241,1.000000,-0.000162,0.003186
sleep_quality,-0.001880,0.001651,0.000222,-0.000679,-0.002641,0.001241,0.002597,0.003308,0.002245,0.000921,-0.002784,-0.000162,1.000000,-0.005179
burnout_level,-0.001625,-0.000061,-0.001361,-0.000609,0.003205,0.000833,-0.003005,0.001229,0.001017,-0.004231,0.000226,0.003186,-0.005179,1.000000

# Scaling

In [123]:
numerical_cols=['age','daily_study_hours','daily_sleep_hours','screen_time_hours','stress_level','anxiety_score','academic_pressure_score','social_support_score','physical_activity_hours']
scaler=StandardScaler()
df_encoded[numerical_cols]=scaler.fit_transform(df_encoded[numerical_cols])

# Final Dataset Validation

In [124]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      150000 non-null  float64
 1   gender                   150000 non-null  int64
 2   year                     150000 non-null  int64
 3   daily_study_hours        150000 non-null  float64
 4   daily_sleep_hours        150000 non-null  float64
 5   screen_time_hours        150000 non-null  float64
 6   stress_level             150000 non-null  float64
 7   anxiety_score            150000 non-null  float64
 8   depression_score         150000 non-null  int64
 9   academic_pressure_score  150000 non-null  float64
 10  social_support_score     150000 non-null  float64
 11  physical_activity_hours  150000 non-null  float64
 12  sleep_quality            150000 non-null  int64
 13  burnout_level            150000 non-null  int64
dtypes: float64(9), int64(5)
memory usage: 16.0 MB

In [125]:
df_encoded.head()

,age,gender,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,social_support_score,physical_activity_hours,sleep_quality,burnout_level
0,0.774684,1,0,-0.465355,0.208220,-0.126715,1.219761,1.568648,3,-0.524228,0.168592,1.385272,0,0
1,-0.387563,1,2,-1.582638,-1.246221,-1.101884,1.219761,-1.216288,10,0.866827,1.213712,1.558024,2,1
2,1.162099,0,3,-0.696517,-1.176962,-1.573739,-1.230870,-1.216288,7,0.866827,-0.876528,-0.342248,1,0
3,-0.000147,1,3,-1.505584,0.138960,0.156398,1.219761,-0.868171,3,-0.524228,1.213712,-0.515000,2,0
4,0.774684,2,3,-1.351476,0.138960,-0.346914,1.219761,0.524297,7,0.171299,-0.528155,1.212520,1,1

In [126]:
df_encoded.shape

(150000, 14)

# Saving final_model_dataset.csv

In [130]:
df_encoded.to_csv('/content/processed/final_model_dataset.csv',index=False)